### ISSUE TITLE
Support dart 2.0

### ISSUE THREAD

**Issue by tiholic** [rinukkusu/simple_moment#4]
Please provide support for dart 2.0 and make compatible with latest flutter release

**Comment by rinukkusu** [comment]
This repository already contains updated code.

Sadly [I can't currently push updates to Pub](https://github.com/dart-lang/pub-dartlang-dart/issues/1460), but until it's resolved you can reference this repository directly in your dependencies:

```yaml
dependencies:
  simple_moment:
    git: https://github.com/rinukkusu/simple_moment
```
